name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Requirements
      run: brew install doxygen
        && pip3 install -r docsDoxySphinx/requirements.txt
    - name: Build docs
      run: cd docsDoxySphinx
        && make html
